# This is a TOML document.

#the Broker config for start
brokerClusterName="DefaultCluster"
brokerName="broker-a"
brokerId=1
deleteWhen=04
fileReservedTime=48
brokerRole="SLAVE"
flushDiskType="SYNC_FLUSH"
autoCreateTopicEnable=true

#smartgoDataPath="/home/smartgo/data"
#brokerPort=10911