# This is a TOML document.

#the Broker config for start
brokerClusterName="DefaultCluster"
brokerName="broker-b"
brokerId=0
deleteWhen=04
fileReservedTime=48
brokerRole="SYNC_MASTER"
flushDiskType="SYNC_FLUSH"
autoCreateTopicEnable=true

storePathRootDir="/home/smartgo/store"
#brokerPort=10911
#brokerIp="10.122.1.210"
#haMasterAddress="10.122.1.210:10912"