# This is a TOML document.

#the Broker config for start
brokerClusterName="DefaultCluster"
brokerName="broker-a"
brokerId=0
deleteWhen=04
fileReservedTime=48
brokerRole="SYNC_MASTER"
flushDiskType="SYNC_FLUSH"
autoCreateTopicEnable=true

#smartgoDataPath="/root/namesrv"
#brokerPort=10911