# This is a TOML document.

#Broker的配置信息
brokerClusterName="DefaultCluster"
brokerName="broker-a"
brokerId=0
deleteWhen=04
fileReservedTime=48
brokerRole="SYNC_MASTER"
flushDiskType="SYNC_FLUSH"
autoCreateTopicEnable=true